cmake_minimum_required(VERSION 3.8)
project(persistent_semantic_mapping)
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 17)
endif()
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(visualization_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
include_directories(include)
add_library(voxel_map src/voxel_map.cpp)
add_executable(persistent_semantic_mapping_node src/persistent_semantic_mapping_node.cpp)
target_link_libraries(persistent_semantic_mapping_node voxel_map)
ament_target_dependencies(persistent_semantic_mapping_node rclcpp sensor_msgs std_msgs visualization_msgs geometry_msgs)
install(TARGETS voxel_map persistent_semantic_mapping_node DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY include/ DESTINATION include)
install(DIRECTORY config launch rviz docs DESTINATION share/${PROJECT_NAME})
ament_package()
